import json
import os
from pathlib import Path

from dotenv import load_dotenv
from groq import Groq

BASE_DIR = Path(__file__).resolve().parent.parent
CONTEXT_FILE = BASE_DIR / "reports" / "ai_business_context.json"
OUTPUT_FILE = BASE_DIR / "reports" / "ai_business_insights.md"

load_dotenv(BASE_DIR / ".env")

api_key = os.getenv("GROQ_API_KEY")

if not api_key:
    raise RuntimeError("GROQ_API_KEY is not configured.")

with open(CONTEXT_FILE, "r", encoding="utf-8") as file:
    context = json.load(file)

prompt = f"""
You are a Business Intelligence Analyst generating an executive report
from a validated analytics dataset.

Your job is to explain the supplied results accurately, not to invent
additional business facts.

STRICT DATA-GROUNDING RULES:

1. Use ONLY numerical values and facts explicitly provided in the
   BUSINESS ANALYTICS CONTEXT.
2. Never invent, estimate, approximate, or recalculate a number when the
   required value is not provided.
3. Never leave incomplete calculations, placeholders, question marks,
   or unfinished values in the final report.
4. Treat Python-generated metrics as authoritative.
5. If a requested metric is not available in the context, say:
   "Not available in the supplied dataset."
6. Distinguish clearly between:
   - Observed fact
   - Possible explanation
   - Recommendation
7. Do not claim causation from correlation or from a single observation.
8. Do not describe a region as "consistently" outperforming another
   region unless the supplied data explicitly proves this.
9. Do not recommend additional marketing spend, hiring, inventory
   increases, or other resource allocation unless the supplied data
   provides evidence supporting that recommendation.
10. Do not introduce external business knowledge as if it were observed
    in this dataset.
11. For anomalies, report the supplied anomaly metric and explain that
    it is a statistical flag, not proof of a business cause.
12. Preserve the exact revenue values supplied in the context.
13. Use Indian Rupee formatting where appropriate.
14. Keep the report concise and suitable for business stakeholders.

IMPORTANT:
The supplied analytics context was generated by deterministic Python
and SQL analytics. Treat it as the source of truth.

Return exactly these sections:

# AI Business Analyst Report

## Executive Summary

Summarize the most important validated business metrics.

## Key Business Findings

List only findings directly supported by the supplied data.

## Revenue Trends

Describe the observed monthly revenue pattern, growth/decline metrics,
and detected anomalies. Do not invent causes.

## Regional Performance

Compare regional revenue using the supplied values and shares.
Do not infer market penetration, customer behavior, or product mix
unless explicitly provided.

## Category Performance

Compare category revenue using the supplied values and shares.
Do not infer margins or profitability.

## Anomalies & Data Quality

Report the supplied anomaly and all supplied data-quality metrics.
Explain why data quality matters without inventing downstream impacts.

## Recommended Actions

Provide practical actions directly connected to the observed data.
Recommendations must be framed as actions to investigate, monitor,
validate, or analyze further when the dataset does not establish a
business cause.

BUSINESS ANALYTICS CONTEXT:
{json.dumps(context, indent=2, ensure_ascii=False)}
"""

client = Groq(api_key=api_key)

response = client.chat.completions.create(
    model="openai/gpt-oss-120b",
    messages=[
        {
            "role": "system",
            "content": "You are a careful business intelligence analyst. "
                       "Use only the supplied data and never invent facts."
        },
        {
            "role": "user",
            "content": prompt
        }
    ],
    temperature=0.2,
)

report = response.choices[0].message.content

if not report:
    raise RuntimeError("The AI model returned an empty response.")

with open(OUTPUT_FILE, "w", encoding="utf-8") as file:
    file.write(report)

print("AI Business Analyst report generated successfully.")
print(f"Report: {OUTPUT_FILE}")